language: python
python: 3.7

dist: xenial

stages:
  - linting
  - test

before_install:
  - make rabbitmq-container
  - make redis-container

install:
  - pip install tox

matrix:
  include:
    - stage: linting
      python: 3.7
      env: TOX_ENV="py37-linting"

    - stage: test
      python: 3.5
      env: TOX_ENV="py35-nameko{2.11,2.12,latest}-redis2.10-test"
    - python: 3.5
      env: TOX_ENV="py35-nameko{2.11,2.12,latest}-redis3.0-test"
    - python: 3.5
      env: TOX_ENV="py35-nameko{2.11,2.12,latest}-redis3.1-test"
    - python: 3.5
      env: TOX_ENV="py35-nameko{2.11,2.12,latest}-redis3.2-test"
    - python: 3.5
      env: TOX_ENV="py35-nameko{2.11,2.12,latest}-redislatest-test"

    - python: 3.6
      env: TOX_ENV="py36-nameko{2.11,2.12,latest}-redis2.10-test"
    - python: 3.6
      env: TOX_ENV="py36-nameko{2.11,2.12,latest}-redis3.0-test"
    - python: 3.6
      env: TOX_ENV="py36-nameko{2.11,2.12,latest}-redis3.1-test"
    - python: 3.6
      env: TOX_ENV="py36-nameko{2.11,2.12,latest}-redis3.2-test"
    - python: 3.6
      env: TOX_ENV="py36-nameko{2.11,2.12,latest}-redislatest-test"

    - python: 3.7
      env: TOX_ENV="py37-nameko{2.11,2.12,latest}-redis2.10-test"
    - python: 3.7
      env: TOX_ENV="py37-nameko{2.11,2.12,latest}-redis3.0-test"
    - python: 3.7
      env: TOX_ENV="py37-nameko{2.11,2.12,latest}-redis3.1-test"
    - python: 3.7
      env: TOX_ENV="py37-nameko{2.11,2.12,latest}-redis3.2-test"
    - python: 3.7
      env: TOX_ENV="py37-nameko{2.11,2.12,latest}-redislatest-test"

script:
  - tox -e $TOX_ENV
