[tool.black]
skip-string-normalization = true
target-version = ['py36', 'py37', 'py38']

[tool.isort]
line_length = 88
include_trailing_comma = true
use_parentheses = true
multi_line_output = 3
force_grid_wrap = 0
# Tests are not included with the package
known_first_party = ["tests"]

[tool.check-manifest]
ignore = ["tests*", "tox.ini", "pyproject.toml", "Makefile"]
